# The 'version' attribute is obsolete and has been removed.
services:
  # PostgreSQL Database Service
  postgres:
    image: postgres:12-alpine
    container_name: bilitioo_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: bilitioo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis Service
  redis:
    image: redis:latest
    container_name: bilitioo_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Elasticsearch Service
  elasticsearch:
    image: elasticsearch:8.15.0
    container_name: elasticsearch
    restart: always
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  # Kibana Service
  kibana:
    image: kibana:8.15.0
    container_name: kibana
    restart: always
    ports:
      - "5601:5601"
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
    depends_on:
      - elasticsearch

  # --- pgAdmin Service Added ---
  pgadmin:
    image: dpage/pgadmin4
    container_name: bilitioo_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  # Main API Service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bilitioo_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - HTTP_SERVER_ADDRESS=0.0.0.0:3000
      - DB_SOURCE=postgresql://root:secret@postgres:5432/bilitioo?sslmode=disable
      - REDIS_ADDRESS=redis:6379
      - ELASTICSEARCH_ADDRESS=http://elasticsearch:9200
    depends_on:
      - postgres
      - redis
      - elasticsearch
    entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/wait-for.sh", "redis:6379", "--", "/app/wait-for.sh", "elasticsearch:9200", "--", "/app/start.sh" ]
    command: [ "/app/main" ]

# Define volumes for persistent data storage
volumes:
  postgres_data:
  redis_data:
  pgadmin_data:
  esdata:
    driver: local
