// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: change_reservation.sql

package db

import (
	"context"
)

const createChangeReservation = `-- name: CreateChangeReservation :one
INSERT INTO "change_reservation" (
    "reservation_id",
    "admin_id",
    "user_id",
    "from_status",
    "to_status"
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, reservation_id, admin_id, user_id, from_status, to_status
`

type CreateChangeReservationParams struct {
	ReservationID int64        `json:"reservation_id"`
	AdminID       int64        `json:"admin_id"`
	UserID        int64        `json:"user_id"`
	FromStatus    TicketStatus `json:"from_status"`
	ToStatus      TicketStatus `json:"to_status"`
}

func (q *Queries) CreateChangeReservation(ctx context.Context, arg CreateChangeReservationParams) (ChangeReservation, error) {
	row := q.db.QueryRowContext(ctx, createChangeReservation,
		arg.ReservationID,
		arg.AdminID,
		arg.UserID,
		arg.FromStatus,
		arg.ToStatus,
	)
	var i ChangeReservation
	err := row.Scan(
		&i.ID,
		&i.ReservationID,
		&i.AdminID,
		&i.UserID,
		&i.FromStatus,
		&i.ToStatus,
	)
	return i, err
}
