// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: payment.sql

package db

import (
	"context"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO "payment" (
    "from_account",
    "to_account",
    "amount"
) VALUES (
    $1, $2, $3
) RETURNING id, from_account, to_account, amount, type, status, created_at
`

type CreatePaymentParams struct {
	FromAccount int64  `json:"from_account"`
	ToAccount   string `json:"to_account"`
	Amount      int64  `json:"amount"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, createPayment, arg.FromAccount, arg.ToAccount, arg.Amount)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.FromAccount,
		&i.ToAccount,
		&i.Amount,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updatePayment = `-- name: UpdatePayment :one
UPDATE "payment"
SET 
    "type" = $1,
    "status" = $2
WHERE id = $3
RETURNING id, from_account, to_account, amount, type, status, created_at
`

type UpdatePaymentParams struct {
	Type   PaymentType   `json:"type"`
	Status PaymentStatus `json:"status"`
	ID     int64         `json:"id"`
}

func (q *Queries) UpdatePayment(ctx context.Context, arg UpdatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, updatePayment, arg.Type, arg.Status, arg.ID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.FromAccount,
		&i.ToAccount,
		&i.Amount,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updatePaymentAmount = `-- name: UpdatePaymentAmount :exec
UPDATE "payment"
SET 
    "amount" = "amount" - $1
WHERE id = $2
`

type UpdatePaymentAmountParams struct {
	Amount int64 `json:"amount"`
	ID     int64 `json:"id"`
}

func (q *Queries) UpdatePaymentAmount(ctx context.Context, arg UpdatePaymentAmountParams) error {
	_, err := q.db.ExecContext(ctx, updatePaymentAmount, arg.Amount, arg.ID)
	return err
}
