// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: payment.sql

package db

import (
	"context"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO "payment" (
    "from_account",
    "to_account",
    "amount"
) VALUES (
    $1, $2, $3
) RETURNING id, from_account, to_account, amount, type, status, created_at
`

type CreatePaymentParams struct {
	FromAccount int64  `json:"from_account"`
	ToAccount   string `json:"to_account"`
	Amount      int64  `json:"amount"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, createPayment, arg.FromAccount, arg.ToAccount, arg.Amount)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.FromAccount,
		&i.ToAccount,
		&i.Amount,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
