// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: penalty.sql

package db

import (
	"context"
)

const getTicketPenalties = `-- name: GetTicketPenalties :one
SELECT p.id, p.vehicle_id, p.penalty_text, p.befor_day, p.after_day 
FROM penalty p
JOIN ticket t ON p.vehicle_id = t.vehicle_id
WHERE t.id = $1
`

func (q *Queries) GetTicketPenalties(ctx context.Context, id int64) (Penalty, error) {
	row := q.db.QueryRowContext(ctx, getTicketPenalties, id)
	var i Penalty
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.PenaltyText,
		&i.BeforDay,
		&i.AfterDay,
	)
	return i, err
}
