// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: report.sql

package db

import (
	"context"
)

const answerReport = `-- name: AnswerReport :one
UPDATE "report"
SET response_text = $1
WHERE id = $2
RETURNING id, reservation_id, user_id, admin_id, request_type, request_text, response_text
`

type AnswerReportParams struct {
	ResponseText string `json:"response_text"`
	ID           int64  `json:"id"`
}

func (q *Queries) AnswerReport(ctx context.Context, arg AnswerReportParams) (Report, error) {
	row := q.db.QueryRowContext(ctx, answerReport, arg.ResponseText, arg.ID)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReservationID,
		&i.UserID,
		&i.AdminID,
		&i.RequestType,
		&i.RequestText,
		&i.ResponseText,
	)
	return i, err
}

const getReports = `-- name: GetReports :many
SELECT id, reservation_id, user_id, admin_id, request_type, request_text, response_text FROM "report"
`

func (q *Queries) GetReports(ctx context.Context) ([]Report, error) {
	rows, err := q.db.QueryContext(ctx, getReports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Report{}
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.ReservationID,
			&i.UserID,
			&i.AdminID,
			&i.RequestType,
			&i.RequestText,
			&i.ResponseText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
