// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: reservation.sql

package db

import (
	"context"
	"time"
)

const createReservation = `-- name: CreateReservation :one
INSERT INTO "reservation" (
    "user_id",
    "ticket_id",
    "payment_id"
) VALUES (
    $1, $2, $3
) RETURNING 
    id, 
    user_id, 
    ticket_id, 
    payment_id, 
    status, 
    EXTRACT(EPOCH FROM duration_time)::bigint as duration_time_seconds,
    created_at
`

type CreateReservationParams struct {
	UserID    int64 `json:"user_id"`
	TicketID  int64 `json:"ticket_id"`
	PaymentID int64 `json:"payment_id"`
}

type CreateReservationRow struct {
	ID                  int64        `json:"id"`
	UserID              int64        `json:"user_id"`
	TicketID            int64        `json:"ticket_id"`
	PaymentID           int64        `json:"payment_id"`
	Status              TicketStatus `json:"status"`
	DurationTimeSeconds int64        `json:"duration_time_seconds"`
	CreatedAt           time.Time    `json:"created_at"`
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (CreateReservationRow, error) {
	row := q.db.QueryRowContext(ctx, createReservation, arg.UserID, arg.TicketID, arg.PaymentID)
	var i CreateReservationRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TicketID,
		&i.PaymentID,
		&i.Status,
		&i.DurationTimeSeconds,
		&i.CreatedAt,
	)
	return i, err
}
