basePath: /
definitions:
  api.CityResponse:
    properties:
      county:
        type: string
      province:
        type: string
    type: object
  api.cancelReservationResponse:
    properties:
      amount_refunded:
        type: integer
      change_reservation:
        $ref: '#/definitions/db.ChangeReservation'
      message:
        type: string
      ticket_id:
        type: integer
    type: object
  api.payPaymentRequest:
    properties:
      payment_id:
        type: integer
      payment_status:
        enum:
        - PENDING
        - COMPLETED
        - FAILED
        - REFUNDED
        type: string
      reservation_status:
        enum:
        - RESERVED
        - RESERVING
        - CANCELED
        - CANCELED-BY-TIME
        type: string
      type:
        enum:
        - CASH
        - CREDIT_CARD
        - WALLET
        - BANK_TRANSFER
        - CRYPTO
        type: string
      user_activity_id:
        type: integer
    required:
    - payment_id
    - payment_status
    - reservation_status
    - type
    type: object
  api.searchTicketsByCitiesRequest:
    properties:
      destination_city_id:
        type: integer
      origin_city_id:
        type: integer
      vehicle_type:
        enum:
        - BUS
        - AIRPLANE
        - TRAIN
        type: string
    required:
    - destination_city_id
    - origin_city_id
    - vehicle_type
    type: object
  db.ChangeReservation:
    properties:
      admin_id:
        type: integer
      from_status:
        $ref: '#/definitions/db.TicketStatus'
      id:
        type: integer
      reservation_id:
        type: integer
      to_status:
        $ref: '#/definitions/db.TicketStatus'
      user_id:
        type: integer
    type: object
  db.CheckReservationTicketStatus:
    enum:
    - RESERVED
    - NOT_RESERVED
    type: string
    x-enum-varnames:
    - CheckReservationTicketStatusRESERVED
    - CheckReservationTicketStatusNOTRESERVED
  db.Penalty:
    properties:
      after_day:
        type: integer
      befor_day:
        type: integer
      id:
        type: integer
      penalty_text:
        type: string
      vehicle_id:
        type: integer
    type: object
  db.SearchTicketsByCitiesRow:
    properties:
      amount:
        type: integer
      arrival_time:
        type: string
      capacity:
        type: integer
      company_name:
        type: string
      departure_time:
        type: string
      destination_city_id:
        type: integer
      destination_county:
        type: string
      destination_province:
        type: string
      origin_city_id:
        type: integer
      origin_county:
        type: string
      origin_province:
        type: string
      route_id:
        type: integer
      status:
        $ref: '#/definitions/db.CheckReservationTicketStatus'
      ticket_id:
        type: integer
      vehicle_type:
        $ref: '#/definitions/db.VehicleType'
    type: object
  db.TicketStatus:
    enum:
    - RESERVED
    - RESERVING
    - CANCELED
    - CANCELED-BY-TIME
    type: string
    x-enum-varnames:
    - TicketStatusRESERVED
    - TicketStatusRESERVING
    - TicketStatusCANCELED
    - TicketStatusCANCELEDBYTIME
  db.VehicleType:
    enum:
    - BUS
    - TRAIN
    - AIRPLANE
    type: string
    x-enum-varnames:
    - VehicleTypeBUS
    - VehicleTypeTRAIN
    - VehicleTypeAIRPLANE
host: localhost:3000
info:
  contact:
    email: support@example.com
    name: API Support
    url: http://www.example.com/support
  description: API for Bilitio ticket booking system.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://localhost:3000/swagger/index.html
  title: Bilitio API
  version: "1.0"
paths:
  /city:
    get:
      consumes:
      - application/json
      description: Returns a list of all cities available for booking.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api.CityResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all cities
      tags:
      - Cities
  /payment:
    post:
      consumes:
      - application/json
      description: Updates payment and reservation status. Requires authentication.
      parameters:
      - description: Payment request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.payPaymentRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Pay for a reservation
      tags:
      - Payment
  /penalty/{ticket_id}:
    put:
      consumes:
      - application/json
      description: Cancel a ticket reservation and calculate penalty refund. Requires
        authentication.
      parameters:
      - description: Ticket ID
        in: path
        name: ticket_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.cancelReservationResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Cancel a reservation
      tags:
      - Reservation
  /ticket-penalties/{ticket_id}:
    get:
      consumes:
      - application/json
      description: Retrieve penalties associated with a specific ticket. Requires
        authentication.
      parameters:
      - description: Ticket ID
        in: path
        name: ticket_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: List of penalties
          schema:
            items:
              $ref: '#/definitions/db.Penalty'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get penalties for a ticket
      tags:
      - Penalties
  /tickets/search:
    post:
      consumes:
      - application/json
      description: Search tickets by origin city, destination city, and vehicle type.
      parameters:
      - description: Search request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.searchTicketsByCitiesRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/db.SearchTicketsByCitiesRow'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Search tickets
      tags:
      - Tickets
  /verify-email:
    post:
      consumes:
      - application/json
      description: Confirms email ownership by validating a verification code. Requires
        authentication if user is logged in.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Verify user email
      tags:
      - Users
schemes:
- http
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
